project:
  type: book
  output-dir: _book

book:
  title: "Solid Propellant Rocket Motors: Internal Ballistics"
  author: "Troy Altus"
  date: today
  chapters:
    - index.qmd
    - chapters/01-intro.qmd
    - chapters/02-propellants.qmd
    - chapters/03-grain-design.qmd
    - chapters/04-internal-ballistics.qmd
    - chapters/05-burning-rate-and-kn.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    number-depth: 3
  pdf:
    documentclass: scrreprt
    number-sections: true
    number-depth: 3